"""Make confirmed_at non-nullable with default

Revision ID: 227cecd7d3f8
Revises: 79bd0e1f622c
Create Date: 2026-03-15 16:48:03.542088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '227cecd7d3f8'
down_revision = '79bd0e1f622c'
branch_labels = None
depends_on = None


def upgrade():
    # First, update any NULL values to current time
    op.execute("UPDATE \"user\" SET confirmed_at = NOW() WHERE confirmed_at IS NULL")
    
    # Then make the column non-nullable
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('confirmed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('confirmed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
