"""Add is_published field to Post model

Revision ID: f6c27f14017f
Revises: abb95de76255
Create Date: 2026-03-24 18:53:13.554577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c27f14017f'
down_revision = 'abb95de76255'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('post', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.execute("UPDATE post SET is_published = TRUE WHERE is_published IS NULL")
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('is_published', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('is_published')

    # ### end Alembic commands ###
